Dev aardvark
cmu-delphi/covid-19-forecast pull request #26
Opened 2020-11-25 21:31 UTC by capolitsch

aardvark package now compatible with evalcast when using usa-facts signals. still problems with JHU signals?

2020-11-25 22:43 UTC, dajmcdon commented
@capolitsch The R checks are failing. Seems to be an issue with one of the examples. Can you fix it up (good practice is to rerun the R CMD check locally by, for example, clicking the button next "Build" in Rstudio. 

Is this still not working with JHU? October 1 seems to be an unfortunately troublesome date in the API for some reason.

2020-11-25 22:54 UTC, capnrefsmmat commented
If there's anything wrong with the JHU data currently in the API (not just that JHU reported something weird on that day, but that our version is wrong), please file an indicators issue -- I don't think engineering is currently tracking any remaining problems after the outage a few weeks ago.

2020-11-26 01:59 UTC, dajmcdon commented
I'm not aware of any issues at the moment. There was an issue with October 1, but currently seems fine for cases/deaths, usa-facts/jhu-csse. I'm not sure what Collin's comment above is referring to.

2020-11-28 17:18 UTC, capolitsch commented
Thanks for the ping. I'm investigating and will keep you posted.

2020-12-08 23:34 UTC, dajmcdon commented
@capolitsch What's the status of this PR?

2020-12-15 21:30 UTC, capolitsch commented
@dajmcdon @jsharpna All checks pass and the forecaster is running as expected. Ready for view.

2020-12-15 21:51 UTC, dajmcdon commented
@capolitsch How challenging will it be to use the newer `evalcast`?

2020-12-16 00:09 UTC, capolitsch commented
@dajmcdon This runs with `evalcast-killcards`. Are there other changes coming to `evalcast`?

2020-12-16 23:01 UTC, dajmcdon requested changes
A few minor things, but otherwise, I approve. @jsharpna, this PR merges in zookeeper from the `fcast-utils` branch. How do you feel about that? I don't particularly have a problem.

2020-12-17 02:48 UTC, capolitsch commented on forecasters/aardvark/DESCRIPTION
> +Remotes: cmu-delphi/covidcast/R-packages/evalcast@evalcast,
Ahh yes, this is true. This is an oversight, but the only consequence is that it uses the main `evalcast` branch for the calls to `get_target_period`. Externally I am using `evalcast-killcards` for `get_predictions` and `plot_trajectory`.

2020-12-17 02:57 UTC, capolitsch commented on forecasters/aardvark/R/bootstrapping.R
> +      mutate(time_value = NA)
Fixed

2020-12-17 02:58 UTC, capolitsch commented on forecasters/aardvark/R/modeling.R
> +#' @importFrom Matrix Matrix
Fixed

2020-12-17 03:00 UTC, capolitsch commented on forecasters/aardvark/R/time_alignment.R
> +# Each aligner should satisfy the "aligner guarantee".
Probably still pretty important, but we likely need to update the way we do it. Planning to experiment with this during improvements.

2020-12-17 03:16 UTC, capolitsch commented on forecasters/aardvark/R/modeling.R
> +                                                                             covidcast::state_census$ABBR)],
Nice. I updated it.

2020-12-17 13:22 UTC, capolitsch commented on forecasters/aardvark/DESCRIPTION
> +Remotes: cmu-delphi/covidcast/R-packages/evalcast@evalcast,
Fixed.

2020-12-17 14:34 UTC, capolitsch reviewed
All changes addressed

2020-12-17 16:32 UTC, dajmcdon approved these changes

2020-12-17 18:58 UTC, merged